### ISSUE TITLE
Create a "My Account" page

### ISSUE THREAD

**Issue by seofernando25** [SeoFernando25/dcms-g6#12]
The "My Account" page should allow the user to:
- [x] Manage his own account (view his personal information, edit, delete it, etc)
- [x] Edit some of his information based on person table (at your discretion)
- [x] Have validated fields (eg: Valid SSN, E-mail, DOB, etc)
Extras
- [ ] Able to delete his own account
- [x] ~~Auto-save changes (without requiring to presss any "save" button)~~

**Comment by Zayood** [comment]
Upcoming Appointments tables needs to be done

**Comment by HenryChen666** [comment]
Done
