### ISSUE TITLE
Prompt user to enter extra information after login

### ISSUE THREAD

**Issue by seofernando25** [SeoFernando25/dcms-g6#2]
It should also apply to someone that: 
- Has created an account
- Closed the page before entering information
- Logged back in

Edit: We should also allow the user to be an employee or a patient

**Comment by Zayood** [comment]
- Some validation for registering.

**Comment by seofernando25** [comment]
Fixed by:
https://github.com/SeoFernando25/dcms-g6/commit/980a634da41e4d7be9a639d7443c4fac3673a24c

User is now redirected to my account page.

Reopen this issue if you want to add something else
