### ISSUE TITLE
Create an appointment search/list for employees

### ISSUE THREAD

**Issue by Zayood** [SeoFernando25/dcms-g6#32]
The appointment should indicate the patient, dentist, date, start time, end time, appointment type, status (no show, cancelled,
completed, unscheduled), and room assigned.

An appointment can have multiple appointment procedures

**Comment by HenryChen666** [comment]
Done

**Comment by HenryChen666** [comment]
Need to be able to edit / update appointment

**Comment by HenryChen666** [comment]
Fixed. 
Already merge to the main branch
